{{- if .Values.flexget.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-flexget-config
data:
  {{ (.Files.Glob "{{config/flexget-config.yml}}").AsConfig | nindent 2}}
{{- end }}