{{- if .Values.flexget.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-flexget-config
data:
  config.yml: |-
  {{- $configFile := printf .Values.flexget.configFile }}
  {{ (.Files.Get $configFile) | nindent 4 }}
{{- end }}