apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-downloader
  labels:
    app: {{ .Release.Name }}-downloader
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-downloader
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-downloader
      annotations:
        # invokes a redeployment if configuration changes
        {{- $configFile := printf .Values.flexget.configFile }}
        config: {{ sha256sum (.Files.Get $configFile) }}
    spec:

      dnsConfig:
        nameservers:
          {{- range .Values.dns.nameservers }}
          - {{ . }}
          {{- end }}

      volumes:
      - name: downloader-config
        configMap:
          name: {{ .Release.Name }}-downloader-config

      - name: transmission-data
      {{- if .Values.storage.data.transmission.persistentVolume.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc-transmission-data
      {{- else }}
        emptyDir: {}
      {{- end }}

      - name: downloads-destination
      {{- if .Values.storage.downloads.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc-downloads
      {{- else }}
        emptyDir: {}
      {{- end }}

      - name: flexget-config
        configMap:
          name: {{ .Release.Name }}-flexget-config

      {{ if .Values.storage.data.flexget.persistentVolume.enabled }}
      - name: flexget-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc-flexget-data
      {{ end }}

      {{ if .Values.storage.extraVolumes.transmission }}
{{ toYaml .Values.storage.extraVolumes.transmission | indent 6 }}
      {{ end }}

      containers:
        - name: ovpn-transmission
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent

          resources:
            {{- toYaml .Values.transmission.resources | nindent 12 }}
            
          securityContext:
            capabilities:
              add: 
                - NET_ADMIN

          volumeMounts:
            - name: downloader-config
              mountPath: /etc/openvpn/user.txt
              subPath: user.txt

            - name: downloader-config
              mountPath: /etc/transmission/settings.json
              subPath: settings.json

            - name: transmission-data
              mountPath: /etc/transmission

            - name: downloads-destination
              mountPath: {{ .Values.transmission.downloads.directory }}

            {{ if .Values.transmission.extraVolumeMounts }}
{{- toYaml .Values.storage.extraVolumeMounts.transmission | nindent 12 }}
            {{- end }}

          env:
            - name: TZ
              value: "{{ .Values.tz }}"
            - name: VPN_PROTO
              value: {{ .Values.vpn.protocol }}
            - name: VPN_SERVER
              value: {{ .Values.vpn.server }}

          ports:
            - name: transmission-ui
              containerPort: 9091
              protocol: TCP

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - ifconfig | grep tun0
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 20

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                # - ping -c 2 google.com
                # TODO: check if flexget is reachable if enabled
                - ifconfig | grep tun0 && curl localhost:9091
            initialDelaySeconds: 30
            periodSeconds: 10

        {{ if .Values.flexget.enabled }}
        - name: flexget
          image: {{ .Values.flexget.image }}
          command: ["/bin/sh","-c"]
          args: ["flexget check && flexget web passwd {{ .Values.flexget.webPassword }} && flexget daemon start"]
          env:
            - name: TZ
              value: "{{ .Values.tz }}"
            - name: FLEXGET_LOG_LEVEL
              value: "debug"
          volumeMounts:
          {{- if .Values.storage.data.flexget.persistentVolume.enabled }}
            - name: flexget-data
              mountPath: /root/.flexget
          {{- end }}
            - name: flexget-config
              mountPath: /root/.flexget/config.yml
              subPath: config.yml
          ports:
            - name: flexget-ui
              containerPort: 5050
              protocol: TCP
          resources:
            {{- toYaml .Values.flexget.resources | nindent 12 }}
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{ end }}
