{{- if .Values.storage.downloads.enabled -}}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-pv-downloads
  labels:
spec:
  storageClassName: existing-pv
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ .Release.Name }}-pvc-downloads
  capacity:
    storage: {{ .Values.storage.downloads.storageSize }}
  accessModes:
    - ReadWriteOnce

  {{- with .Values.storage.downloads.volume }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end -}}