kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-transmission-data
  annotations:
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi