kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-videos
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.download.size }}