apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-openvpn-config
type: Opaque
data:
  config.ovpn: |
    {{- $configFile := printf .Values.vpn.configFile }}
    {{ .Files.Get $configFile | b64enc }}
    
  user.txt: |
    {{ $vpnCreds := printf "%s\n%s" .Values.vpn.username .Values.vpn.password -}}
    {{ $vpnCreds | b64enc }}
