apiVersion: k3d.io/v1alpha2 # this will change in the future as we make everything more stable
kind: Simple # internally, we also have a Cluster config, which is not yet available externally
name: downloader-cluster # name that you want to give to your cluster (will still be prefixed with `k3d-`)
image: rancher/k3s:v1.17.0-k3s.1
servers: 1
agents: 1