# Default values for openvpn-transmission.

image: openvpn-transmission:latest

tz: America/Los_Angeles

vpn:
  username:
  password:
  protocol: UDP
  server: USA-LOS.ANGELES

transmission:
  resources:
    requests:
      cpu: "1"
      memory: "32Mi"
    limits:
      cpu: "1"
      memory: "128Mi"
  rpc:
    whitelistSubnet:
    whitelistHost:
      enabled: true
      dnsNames: "*"
  peer:
    limit:
      global: 500
      perTorrent: 50
  alt:
    speed:
      down: 100
      up: 0
  speed:
    limit:
      down: 5000
      up: 0
  downloads:
    queueSize: 10
    directory: /downloads
  ratio:
    limit: 0

flexget:
  enabled: false
  image: flexget:v3.1.135
  webPassword: test123456test
  resources:
    requests:
      memory: "64Mi"
    limits:
      cpu: "1"
      memory: "96Mi"

dns:
  nameservers:
    - 1.1.1.1

storage:
  storageClassName: 

  data:
    transmission:
      persistentVolume:
        enabled: false
        storageSize: 1Gi
    flexget:
      persistentVolume:
        enabled: false
        storageSize: 1Gi

  downloads:
    enabled: false
    storageSize: 10Gi
    volume: {}

service:
  ip:
  transmissionPort: 80
  flexgetPort: 5050

replicaCount: 1

nodeSelector: {}

tolerations: []

affinity: {}
