# Default values for openvpn-transmission.

vpn:
  username:
  password:
  protocol: UDP
  server: USA-LOS.ANGELES
transmission:
  rpc:
    whitelistSubnet:
    whitelistHost:
      enabled: true
      dnsNames: "*"
  peer:
    limit:
      global: 500
      perTorrent: 50
  alt:
    speed:
      down: 100
      up: 0
  speed:
    limit:
      down: 5000
      up: 0
  download:
    queueSize: 10
    directory: /downloads
  ratio:
    limit: 0

dns:
  nameservers:
    - 1.1.1.1

storage:
  persistentVolume:
    enabled: true
  storageClassName: manual
  download:
    path:
    server: 
    size: 1Mi

service:
  ip:
  port: 80


replicaCount: 1

resources:
  requests:
    cpu: "1"
    memory: "64Mi"
  limits:
    cpu: "2"
    memory: "128Mi"

image:
  repo: openvpn-transmission
  tag: latest

nodeSelector: {}

tolerations: []

affinity: {}
